enum eFACTION {
    NONE = 0,
    PLAYER = 1,
    IMPERIUM = 2,
    MECHANICUS = 3,
    INQUISITION = 4,
    ECCLESIARCHY = 5,
    ELDAR = 6,
    ORK = 7,
    TAU = 8,
    TYRANIDS = 9,
    CHAOS = 10,
    HERETICS = 11,
    GENESTEALER = 12,
    NECRONS = 13,
    _COUNT,
}

enum eGENDER {
    FEMALE,
    MALE,
    NEUTRAL,
}

enum eROLE {
    NONE = 0,
    CHAPTERMASTER = 1,
    HONOURGUARD = 2,
    VETERAN = 3,
    TERMINATOR = 4,
    CAPTAIN = 5,
    DREADNOUGHT = 6,
    CHAMPION = 7,
    TACTICAL = 8,
    DEVASTATOR = 9,
    ASSAULT = 10,
    ANCIENT = 11,
    SCOUT = 12,
    CHAPLAIN = 14,
    APOTHECARY = 15,
    TECHMARINE = 16,
    LIBRARIAN = 17,
    SERGEANT = 18,
    VETERANSERGEANT = 19,
    FORGEMASTER,
    CHIEFLIBRARIAN,
    MASTERAPOTHECARY,
    MASTERCHAPLAIN,
    CODICIERY,
    LEXICANUM,
    LIBRARIANASPIRANT,
    APOTHECARYASPIRANT,
    CHAPLAINASPIRANT,
    TECHMARINEASPIRANT,
    MARINEEND,
    LANDRAIDER = 50,
    RHINO = 51,
    PREDATOR = 52,
    LANDSPEEDER = 53,
    WHIRLWIND = 54,
}
enum eMENU {
    DEFAULT = 0,
    MANAGE = 1,
    TURN_END = 2,
    WELCOME_SCREEN1 = 3,
    WELCOME_SCREEN2 = 4,
    WELCOME_SCREEN3 = 5,
    WELCOME_SCREEN4 = 6,
    APOTHECARION = 11,
    RECLUSIAM = 12,
    LIBRARIUM = 13,
    ARMAMENTARIUM = 14,
    RECRUITING = 15,
    FLEET = 16,
    EVENT_LOG = 17,
    FESTIVAL = 18,
    DIPLOMACY = 20,
    SETTINGS = 21,
    COMPANY_SETTINGS = 22,
    ROLE_SETTINGS = 23,
    FORMATIONS_SETTINGS = 24,
    GAME_HELP = 30,
    CHAPTER_MASTER = 50,
    SECRET_LAIR = 60,
}

enum eLUCK {
    BAD = -1,
    NEUTRAL = 0,
    GOOD = 1,
}

enum eINQUISITION_MISSION {
    PURGE,
    INQUISITOR,
    SPYRER,
    ARTIFACT,
    TOMB_WORLD,
    TYRANID_ORGANISM,
    ETHEREAL,
    DEMON_WORLD,
    RANDOM = 100,
}

enum eEVENT {
    //GOOD
    SPACE_HULK,
    PROMOTION,
    STRANGE_BUILDING,
    SORORITAS,
    ROGUE_TRADER,
    INQUISITION_MISSION,
    INQUISITION_PLANET,
    MECHANICUS_MISSION,
    //NEUTRAL
    STRANGE_BEHAVIOR,
    FLEET_DELAY,
    HARLEQUINS,
    SUCCESSION_WAR,
    RANDOM_FUN,
    //BAD
    WARP_STORMS,
    ENEMY_FORCES,
    CRUSADE,
    ENEMY,
    MUTATION,
    SHIP_LOST,
    CHAOS_INVASION,
    NECRON_AWAKEN,
    FALLEN,
    //END
    NONE,
}

enum eIN_GAME_MENU_EFFECT {
    SAVE = 11,
    LOAD = 12,
    OPTIONS = 13,
    EXIT = 14,
    RETURN = 15,
    BACK_FROM_SAVELOAD = 18,
    BACK_FROM_SETTINGS = 25,
    CLOSE_SAVELOAD = 30,
}

enum eEQUIPMENT_SLOT {
    WEAPON_ONE,
    WEAPON_TWO,
    ARMOUR,
    GEAR,
    MOBILITY,
    ALL,
}

enum eLIVERY_SELECTION_TYPES {
    DEFAULT,
    BY_ROLE,
    BY_COMPANY,
}

enum eLIVERY_COLOURING_OPTIONS {
    STANDARD,
    BULK,
    ADVANCED,
}
