function scr_ship_name(argument0) {

	var temp;temp="";


	if (argument0="imperial"){

	    var rand;rand=floor(random(211))+1;
    
	    if (rand=1) then temp="Magnificent of Glorious";
	    if (rand=2) then temp="Mortality Venom";
	    if (rand=3) then temp="Hero of Blazer";
	    if (rand=4) then temp="Flame Terror";
	    if (rand=5) then temp="Scourge of Barracuda";
	    if (rand=6) then temp="Menacing Ethereal";
	    if (rand=7) then temp="Mourning Seduction";
	    if (rand=8) then temp="Audacious Axe";
	    if (rand=9) then temp="Apollo";
	    if (rand=10) then temp="Vast Fist";
	    if (rand=11) then temp="Pride of Might";
	    if (rand=12) then temp="Chief Tiger";
	    if (rand=13) then temp="His Elegance";
	    if (rand=14) then temp="Arm of Shadow";
	    if (rand=15) then temp="Potent Mourning";
	    if (rand=16) then temp="Greatest Flames";
	    if (rand=17) then temp="Dire Artificial";
	    if (rand=18) then temp="Glowing Defender";
	    if (rand=19) then temp="White Audacious";
	    if (rand=20) then temp="Shield Slayer";
	    if (rand=21) then temp="Potent Shadow";
	    if (rand=22) then temp="Menacing Remembrance";
	    if (rand=23) then temp="Immaterial";
	    if (rand=24) then temp="Skillful Gunner";
	    if (rand=25) then temp="Underworld Giant";
	    if (rand=26) then temp="Destroyer Judgement";
	    if (rand=27) then temp="Bloodied Axe";
	    if (rand=28) then temp="Eternal Slayer";
	    if (rand=29) then temp="Blue Nightmare";
	    if (rand=30) then temp="Astute Arm";
	    if (rand=31) then temp="Dire of Burnished";
	    if (rand=32) then temp="Magnificent Jester";
	    if (rand=33) then temp="Enchanted Salvation";
	    if (rand=34) then temp="Scout Heavens";
	    if (rand=35) then temp="Halberd Serpent";
	    if (rand=36) then temp="Lion of Acheron ";
	    if (rand=37) then temp="Deathbringer";
	    if (rand=38) then temp="Decision Golden";
	    if (rand=39) then temp="Astute Predator";
	    if (rand=40) then temp="Wasp Serpent";
	    if (rand=41) then temp="Black of Red";
	    if (rand=42) then temp="Line of Hell";
	    if (rand=43) then temp="Predator of Tyranid";
	    if (rand=44) then temp="Gleaming of Silver";
	    if (rand=45) then temp="Space of Ethereal";
	    if (rand=46) then temp="Foremost Titan";
	    if (rand=47) then temp="Honoured Bull";
	    if (rand=48) then temp="Astral Shining";
	    if (rand=49) then temp="Mourning Tortured";
	    if (rand=50) then temp="Aurora Slayer";
	    if (rand=51) then temp="Magnificent Artful";
	    if (rand=52) then temp="Baleful Light";
	    if (rand=53) then temp="Flame Heavenly";
	    if (rand=54) then temp="Sin Python";
	    if (rand=55) then temp="Space Shadow";
	    if (rand=56) then temp="Towering Sword";
	    if (rand=57) then temp="Stargazer Pearl";
	    if (rand=58) then temp="Modern Speed";
	    if (rand=59) then temp="Thunder Relinctor";
	    if (rand=60) then temp="Dire Methodical";
	    if (rand=61) then temp="Strange Predator";
	    if (rand=62) then temp="Aurora Avenger";
	    if (rand=63) then temp="Bloodied Dawn";
	    if (rand=64) then temp="Sword Son";
	    if (rand=65) then temp="His Sword";
	    if (rand=66) then temp="Lynx of Heaven";
	    if (rand=67) then temp="God Bull";
	    if (rand=68) then temp="White Serpent";
	    if (rand=69) then temp="Basilisk Face";
	    if (rand=70) then temp="Flame of Sky";
	    if (rand=71) then temp="Wailing Skull";
	    if (rand=72) then temp="Guardian Soldier";
	    if (rand=73) then temp="Magnificent Terminator";
	    if (rand=74) then temp="Scholar Aurora";
	    if (rand=75) then temp="Courageous Defender";
	    if (rand=76) then temp="Adament Lion";
	    if (rand=77) then temp="Burnished Salamander";
	    if (rand=78) then temp="Graceful Crusader";
	    if (rand=79) then temp="Errant of Swift";
	    if (rand=80) then temp="Gleaming Tortured";
	    if (rand=81) then temp="Swooping of Foremost";
	    if (rand=82) then temp="Halberd of Exile";
	    if (rand=83) then temp="Nightmare of the Predator";
	    if (rand=84) then temp="Adament Axe";
	    if (rand=85) then temp="Claw Enchanted";
	    if (rand=86) then temp="Lion of Adder";
	    if (rand=87) then temp="Wailing Falcon";
	    if (rand=88) then temp="Blazer Scorn";
	    if (rand=89) then temp="Fire Mortality";
	    if (rand=90) then temp="Exuberant Revenge";
	    if (rand=91) then temp="The Righteous Zeal";
	    if (rand=92) then temp="Star of Emperor";
	    if (rand=93) then temp="Scorn Hydra";
	    if (rand=94) then temp="Leopard Towering";
	    if (rand=95) then temp="Unreserved";
	    if (rand=96) then temp="Burnished Lance";
	    if (rand=97) then temp="Watcher Spirit";
	    if (rand=98) then temp="The Saint's Pride";
	    if (rand=99) then temp="Peerless Fortitude";
	    if (rand=100) then temp="Undetected Destroyer";
	    if (rand=101) then temp="Grey Imperial";
	    if (rand=102) then temp="Glowing Burnished";
	    if (rand=103) then temp="Swift Light";
	    if (rand=104) then temp="Iron Armour";
	    if (rand=105) then temp="True Aurora";
	    if (rand=106) then temp="Scourge of Remembrance";
	    if (rand=107) then temp="Flames of Dire";
	    if (rand=108) then temp="Foremost Darkling";
	    if (rand=109) then temp="The Holy Endeavour";
	    if (rand=110) then temp="Mentor Fable";
	    if (rand=111) then temp="Swift Fist";
	    if (rand=112) then temp="Skull Blazer";
	    if (rand=113) then temp="Courageous Spirit";
	    if (rand=114) then temp="Exuberant Destroyer";
	    if (rand=115) then temp="Punishment";
	    if (rand=116) then temp="Stallion Warrior";
	    if (rand=117) then temp="Armour Chief";
	    if (rand=118) then temp="Leviathan Torment";
	    if (rand=119) then temp="Silvered of Space";
	    if (rand=120) then temp="Face of Space";
	    if (rand=121) then temp="Imperial Warp";
	    if (rand=122) then temp="Glowing Sky";
	    if (rand=123) then temp="The Blessed Star";
	    if (rand=124) then temp="Wisdom Aurora";
	    if (rand=125) then temp="Harvester of Hydra";
	    if (rand=126) then temp="Ice Wing";
	    if (rand=127) then temp="Eternal Hornet";
	    if (rand=128) then temp="Greatest Restraint";
	    if (rand=129) then temp="Sage Effect";
	    if (rand=130) then temp="Armour Infamous";
	    if (rand=131) then temp="Falcon Lord";
	    if (rand=132) then temp="Stranger";
	    if (rand=133) then temp="Halberd of the Forgotten";
	    if (rand=134) then temp="Apollo of Priest";
	    if (rand=135) then temp="The Litany of Hatred";
	    if (rand=136) then temp="The Ghost of Caliban";
	    if (rand=137) then temp="The Gorgon's Claw";
	    if (rand=138) then temp="The Empire's Blessing";
	    if (rand=139) then temp="Diplomacy";
	    if (rand=140) then temp="Honourable Death";
	    if (rand=141) then temp="His Name";
	    if (rand=142) then temp="Righteous Hammer";
	    if (rand=143) then temp=string(scr_marine_name())+"'s Revenge";
	    if (rand=144) then temp="Typhoon Master";
	    if (rand=145) then temp="Lamenting Flame";
	    if (rand=146) then temp="Sider of Lord";
	    if (rand=147) then temp="Outcast Imperative";
	    if (rand=148) then temp="Sabre of Terror";
	    if (rand=149) then temp="Blazer Honored";
	    if (rand=150) then temp="Flame Royal";
	    if (rand=151) then temp="Revenger Brazen";
	    if (rand=152) then temp="Relictor of Truth";
	    if (rand=153) then temp="Fiend Son";
	    if (rand=154) then temp="Overt Honored";
	    if (rand=155) then temp="Iron Wolf";
	    if (rand=156) then temp="Blood Golden";
	    if (rand=157) then temp="Gate of Great";
	    if (rand=158) then temp="Son of Zealous";
	    if (rand=159) then temp="Chief Pirate";
	    if (rand=160) then temp="Stargazer";
	    if (rand=161) then temp="Mythical Blue";
	    if (rand=162) then temp="Invisible Claw";
	    if (rand=163) then temp="Astral Titan";
	    if (rand=164) then temp="Raptor Guardian";
	    if (rand=165) then temp="Methodical Silver";
	    if (rand=166) then temp="Underworld Warp";
	    if (rand=167) then temp="Bright Retribution";
	    if (rand=168) then temp="Shadow Night";
	    if (rand=169) then temp="Terminator Heart";
	    if (rand=170) then temp="Bright Warp";
	    if (rand=171) then temp="Sacred Phoenix";
	    if (rand=172) then temp="Scourge Slayer";
	    if (rand=173) then temp="Venom Sage";
	    if (rand=174) then temp="Shark Unseen";
	    if (rand=175) then temp="Axe Imperial";
	    if (rand=176) then temp="Decision Asguard";
	    if (rand=177) then temp="Underworld Evil";
	    if (rand=178) then temp="Fabe of Dawnlight";
	    if (rand=179) then temp="Fire Jester";
	    if (rand=180) then temp="His of God";
	    if (rand=181) then temp="Scorn of Salvation";
	    if (rand=182) then temp="Spear Heart";
	    if (rand=183) then temp="Audacious Destiny";
	    if (rand=184) then temp="Swift Mourning";
	    if (rand=185) then temp="Philosophy Void";
	    if (rand=186) then temp="Hornet Claw";
	    if (rand=187) then temp="Vast of Arm";
	    if (rand=188) then temp="Alien Retribution";
	    if (rand=189) then temp="Dark Sin";
	    if (rand=190) then temp="Decision Masterful";
	    if (rand=191) then temp="Lord of Sacred";
	    if (rand=192) then temp="Shining Thunder";
	    if (rand=193) then temp="Baleful Artifical";
	    if (rand=194) then temp="Destiny of Burnished";
	    if (rand=195) then temp="Defender Space";
	    if (rand=196) then temp="Speed of Stone";
	    if (rand=197) then temp="His of Wind";
	    if (rand=198) then temp="Domination of Light";
	    if (rand=199) then temp="Ocelot Blood";
	    if (rand=200) then temp="Blazer of Titan";
	    if (rand=201) then temp="Consul Tortured";
	    if (rand=202) then temp="Question Acheron";
	    if (rand=203) then temp="Golden Mentor";
	    if (rand=204) then temp="Wandering Ethereal";
	    if (rand=205) then temp="Cobra Chief";
	    if (rand=206) then temp="Effect of Myth";
	    if (rand=207) then temp="Errant of Soul";
	    if (rand=208) then temp="Vast Terror";
	    if (rand=209) then temp="Gate Light";
	    if (rand=210) then temp="Hell's Theory";
	    if (rand=211) then temp="Ice Retribution";



	}



	if (argument0="ork"){

	    var rand;rand=floor(random(40))+1;
    
	    if (rand=1) then temp="Da Brutal Kunnin'";
	    if (rand=2) then temp="Starkilla";
	    if (rand=3) then temp="Cutzgutz";
	    if (rand=4) then temp="Space Skorcha";
	    if (rand=5) then temp="Killyboot";
	    if (rand=6) then temp="Planet Smasha";
	    if (rand=7) then temp="Boom Krooza";
	    if (rand=8) then temp="Comet Rokkit";
	    if (rand=9) then temp="Scupa Bam";
	    if (rand=10) then temp="Da Slag Ball";
	    if (rand=11) then temp="Teef Smasha";
	    if (rand=12) then temp="Da Big Bouldah";
	    if (rand=13) then temp="Big Grot Thudda";
	    if (rand=14) then temp="Shreda Boldah";
	    if (rand=15) then temp="Bitz an Piecez";
	    if (rand=16) then temp="Sneky Boldah";
	    if (rand=17) then temp="Wotz Dis Fing";
	    if (rand=18) then temp="Look at Dat";
	    if (rand=19) then temp="Divide and Wot";
	    if (rand=20) then temp="Konkara";
	    if (rand=21) then temp="Big Stinkin Wrek";
	    if (rand=22) then temp="Nail Steala";
	    if (rand=23) then temp="Watch Thiz";
	    if (rand=24) then temp="Shake Makar";
	    if (rand=25) then temp="Da Big One";
	    if (rand=26) then temp="Da Not as Big as Big One But Bigger dan Medium Won";
	    if (rand=27) then temp="Dat One";
	    if (rand=28) then temp="Dis One";
	    if (rand=29) then temp="Dis Other One";
	    if (rand=30) then temp="Rok o Doom";
	    if (rand=31) then temp="Blacktoof";
	    if (rand=32) then temp="Big Scrap Scrappa";
	    if (rand=33) then temp="Ghaz'z Git Killa";
	    if (rand=34) then temp="Fist of Gork";
	    if (rand=35) then temp="Foot of Mork";
	    if (rand=36) then temp="Burna Barge";
	    if (rand=37) then temp="Haknag's Hulk";
	    if (rand=38) then temp="Da Orktrepid";
	    if (rand=39) then temp="Deffhed";
	    if (rand=40) then temp="Keelsmasha";

	}


	if (temp!="") then return(temp);


}
