function scr_imperial_name(argument0) {

	var di,re;
	di=0;
	re="";


	if (argument0=1) then re=scr_marine_name();

	if (argument0=2){di=floor(random(166));
	    if (di=1) then re="Elodia";
	    if (di=2) then re="Sharrel";
	    if (di=3) then re="Louvenia";
	    if (di=4) then re="Tysha";
	    if (di=5) then re="Belia";
	    if (di=6) then re="Patrishana";
	    if (di=7) then re="Erlene";
	    if (di=8) then re="Ilya";
	    if (di=9) then re="Lyddus";
	    if (di=10) then re="Naima";
	    if (di=11) then re="Jassiq";
	    if (di=12) then re="Carie";
	    if (di=13) then re="Farah";
	    if (di=14) then re="Tenaya";
	    if (di=15) then re="Hana";
	    if (di=16) then re="Devona";
	    if (di=17) then re="Vallie";
	    if (di=18) then re="Gard";
	    if (di=19) then re="Kayleigh";
	    if (di=20) then re="Sha";
	    if (di=21) then re="Kelle";
	    if (di=22) then re="Miranda";
	    if (di=23) then re="Furia";
	    if (di=24) then re="Gracia";
	    if (di=25) then re="Cora";
	    if (di=26) then re="Neoma";
	    if (di=27) then re="Keira";
	    if (di=28) then re="Eneida";
	    if (di=29) then re="Belia";
	    if (di=30) then re="Lasce";
	    if (di=31) then re="Leona";
	    if (di=32) then re="Petra";
	    if (di=33) then re="Pearle";
	    if (di=34) then re="Roberta";
	    if (di=35) then re="Kaylene";
	    if (di=36) then re="Dennise";
	    if (di=37) then re="Remillia";
	    if (di=38) then re="Tsalie";
	    if (di=39) then re="Hermine";
	    if (di=40) then re="Kate";
	    if (di=41) then re="Joye";
	    if (di=42) then re="Jacki";
	    if (di=43) then re="Delta";
	    if (di=44) then re="Ignacia";
	    if (di=45) then re="Alpharia";
	    if (di=46) then re="Devona";
	    if (di=47) then re="Marni";
	    if (di=48) then re="Dewyer";
	    if (di=49) then re="Angela";
	    if (di=50) then re="Selphy";
	    if (di=51) then re="Generica";
	    if (di=52) then re="Venus";
	    if (di=53) then re="Maria";
	    if (di=54) then re="Isis";
	    if (di=55) then re="Omegan";
	    if (di=56) then re="Freya";
	    if (di=57) then re="Isabella";
	    if (di=58) then re="Lyra";
	    if (di=59) then re="Victoria";
	    if (di=60) then re="De Shiloh";
	    if (di=61) then re="Nadasha";
	    if (di=62) then re="Rukhsana";
	    if (di=63) then re="Kadene";
	    if (di=64) then re="Tahirah";
	    if (di=65) then re="Vulcana";
	    if (di=66) then re="Sureka";
	    if (di=67) then re="Leaneena";
	    if (di=68) then re="Mersadie";
	    if (di=69) then re="Euphrati";
	    if (di=70) then re="Leona";
	    if (di=71) then re="Keeler";
	    if (di=72) then re="Tarasha";
	    if (di=73) then re="Kallista";
	    if (di=74) then re="Camille";
	    if (di=75) then re="Seriph";
	    if (di=76) then re="Serena";
	    if (di=77) then re="Bequa";
	    if (di=78) then re="Askarid";
	    if (di=79) then re="Coraline";
	    if (di=80) then re="Ske Vris";
	    if (di=81) then re="Cebella";
	    if (di=82) then re="Sarashina";
	    if (di=83) then re="Roxanne";
	    if (di=84) then re="Erephren";
	    if (di=85) then re="Vivyen";
	    if (di=86) then re="Aliva";
	    if (di=87) then re="Vris";
	    if (di=88) then re="Lotarra";
	    if (di=89) then re="Cyrene";
	    if (di=90) then re="Valiane";
	    if (di=91) then re="Theodoria";
	    if (di=92) then re="Ranis";
	    if (di=93) then re="Sophia";
	    if (di=94) then re="Vanax";
	    if (di=95) then re="Shansa";
	    if (di=96) then re="Katt";
	    if (di=97) then re="Nessina";
	    if (di=98) then re="Miska ";
	    if (di=99) then re="Mikaela";
	    if (di=100) then re="Ultima";
	    if (di=101) then re="Gentia";
	    if (di=102) then re="Petra";
	    if (di=103) then re="Abiah";
	    if (di=104) then re="Katherina";
	    if (di=105) then re="Lenneth";
	    if (di=106) then re="Meredith";
	    if (di=107) then re="Xena";
	    if (di=108) then re="Vera";
	    if (di=109) then re="Vivian";
	    if (di=110) then re="Augustina";
	    if (di=111) then re="Marina";
	    if (di=112) then re="Marida";
	    if (di=113) then re="Fiona";
	    if (di=114) then re="Fiela";
	    if (di=115) then re="Ferninda";
	    if (di=116) then re="Severa";
	    if (di=117) then re="Octavia";
	    if (di=118) then re="Domitia";
	    if (di=119) then re="Scribonia";
	    if (di=120) then re="Poppaea";
	    if (di=121) then re="Adrastia";
	    if (di=122) then re="Immolita";
	    if (di=123) then re="Rohesia";
	    if (di=124) then re="Xanthia";
	    if (di=125) then re="Victrix";
	    if (di=126) then re="Vesma";
	    if (di=127) then re="Quirna";
	    if (di=128) then re="Iulia";
	    if (di=129) then re="Jocasta";
	    if (di=130) then re="Liboria";
	    if (di=131) then re="Infernria";
	    if (di=132) then re="Pentitentia";
	    if (di=133) then re="Marci";
	    if (di=134) then re="Pia";
	    if (di=135) then re="Noxia";
	    if (di=136) then re="Clio";
	    if (di=137) then re="Harmonia";
	    if (di=138) then re="Dorcas";
	    if (di=139) then re="Evangelina";
	    if (di=140) then re="Florentina";
	    if (di=141) then re="Hortensia";    
	    if (di=142) then re="Labiya";
	    if (di=143) then re="Gloria";
	    if (di=144) then re="Idesta";
	    if (di=145) then re="Adalheidis";
	    if (di=146) then re="Alcetis";
	    if (di=147) then re="Alecta";
	    if (di=148) then re="Charis";
	    if (di=149) then re="Protona";
	    if (di=150) then re="Caelia";
	    if (di=151) then re="Rika";
	    if (di=152) then re="Svetlana";
	    if (di=153) then re="Helga";
	    if (di=154) then re="Selina";
	    if (di=155) then re="Emmanuelle";
	    if (di=156) then re="Evalyn";
	    if (di=157) then re="Skarlet";
	    if (di=158) then re="Rasputina"; 
	    if (di=159) then re="Messalina";
	    if (di=160) then re="Alicia";
	    if (di=161) then re="Dominica";
	    if (di=162) then re="Morgana";
	    if (di=163) then re="Circe";
	    if (di=164) then re="Isha";
	    if (di=165) then re="Guinevere";
	    if (di=166) then re="Morgaine";   
	}

	// if (argument0!=0) then inquisitor_gender[argument0]=argument0;

	return(re);



}
