name: Gobo Formatter

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  format-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Gobo
        run: |
          gh release download --repo EttyKitty/GoboCat --pattern "gobo-linux-x64.zip"
          unzip gobo-linux-x64.zip
          chmod +x ./gobo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Formatter
        run: |
          ./gobo .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            **/*.gml
          commit-message: "style: Automated Gobo format"
          title: "style: Automated Gobo format"
          body: "This is an automated PR containing formatting updates for all .gml files."
          branch: automation/gobo-format-all
          delete-branch: true
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
